# 配置服务名称
spring:
  application:
    name: admin-eureka

# 端点暴露
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 配置治理服务注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka,http://localhost:1002/eureka