# 定义Spring应用名称，它是一个微服务的名称，一个微服务可拥有多个实例
spring:
  application:
    name: zuul
  # Redis配置
  redis:
    # Redis服务器地址
    host: 192.168.80.130
    # Redis密码
    password: abcdefg
    # Jedis客户端
    jedis:
      # 连接池配置
      pool:
        # 最大活动连接数
        max-active: 20
        # 最大等待时间（单位毫秒）
        max-wait: 2000
        # 最小闲置连接数
        min-idle: 5
        # 最大闲置连接数
        max-idle: 15

# 向端口为5001和5002的Eureka服务治理中心注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5001/eureka, http://localhost:5002/eureka

# Zuul的配置
zuul:
  # 路由配置
  routes:
    # 用户微服务
    user-service:
      # 请求拦截路径配置（使用ANT风格）
      path: /u/**
      # 通过一个URL配置
      url: http://localhost:6001/
    # 产品微服务配置
    fund-service:
      # 请求拦截路径配置（使用ANT风格）
      path: /p/**
      service-id: product

# resilience4j配置
resilience4j:
  ratelimiter:
    limiters:
      # 名称为“user”的限速器
      user:
        # 时间戳内限制通过的请求数，默认为50
        limitForPeriod: 30
        # 配置时间戳，默认值为500 ns
        limitRefreshPeriodInMillis: 5000
        # 超时时间
        timeoutInMillis: 5000