secret:
  # token阴匙
  key: secret
server:
  # 启动端口
  port: 6001

spring:
  application:
    name: client2

eureka:
  client:
    serviceUrl:
      # 注册给Eureka
      defaultZone: http://localhost:1001/eureka,http://localhost:1002/eureka
  instance:
    # 服务器
    hostname: localhost