# 配置启动端口
server:
  port: 1013

# 配置Redis
spring:
  redis:
    # 服务器
    host: 192.168.224.131
    # 密码
    password: 123456
    # jedis配置
    jedis:
      #连接池配置
      pool:
        # 最大活动线程数
        max-active: 20
        # 最大空闲线程数
        max-idle: 10
        # 最小空闲线程数
        min-idle: 5
        # 最大等待1秒
        max-wait: 1s