spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        output:
          destination: TopicTest2
          group: PRODUCER_GROUP_DEMO_2
server:
  port: 8081
