# 定义Spring应用名称，它是一个微服务的名称，一个微服务可拥有多个实例
spring:
  application:
    name: ms-sleuth
#  注册到服务治理中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka,http://localhost:1002/eureka
management:
  metrics:
    web:
      server:
        # 取消自动定时，不设置为false可能时间序列数量增长过大，导致异常
        auto-time-requests: false
# 端口
server:
  port: 9001

# zipkin配置
zipkin:
  storage:
    # 使用ElasticSearch作为存储类型
    type: elasticsearch
    # ElasticSearch配置
    elasticsearch:
      # 索引
      index: zipkin
      # 最大请求数
      max-requests: 64
      # 索引分片数
      index-shards: 5
      # 索引复制数
      index-replicas: 1
      # 服务器和端口
      hosts: localhost:9200