spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: spring-cloud-seata-account
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.216.128:8848
mybatis:
    mapper-locations: classpath*:com/gupaoedu/springcloud/seata/accountprovider/dal/mappers/*Mapper.xml
    type-aliases-package: com.gupaoedu.springcloud.seata.accountprovider.dal.entitys
dubbo:
  application:
    name: spring-cloud-seata-account
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: 20882
  scan:
    base-packages: com.gupaoedu.springcloud.seata.accountprovider.impl