#spring:
#  redis:
#    # 配置哨兵
#    sentinel:
#      # 主服务器名称
#      master: mymaster
#      # 哨兵节点
#      nodes: 192.168.224.131:26379,192.168.224.133:26379,192.168.224.134:26379
#    # 登录密码
#    password: 123456
#    # Jedis配置
#    jedis:
#      # 连接池配置
#      pool:
#        # 最大等待1秒
#        max-wait: 1s
#        # 最大空闲连接数
#        max-idle: 10
#        # 最大活动连接数
#        max-active: 20
#        # 最小空闲连接数
#        min-idle: 5

spring:
  redis:
    # 登录密码
    # Jedis配置
    jedis:
      # 连接池配置
      pool:
        # 最大等待1秒
        max-wait: 1s
        # 最大空闲连接数
        max-idle: 10
        # 最大活动连接数
        max-active: 20
        # 最小空闲连接数
        min-idle: 5
    # 配置Redis集群信息
    cluster:
      # 集群节点信息
      nodes: 192.168.224.135:7001,192.168.224.135:7002,192.168.224.135:7003,192.168.224.135:7004,192.168.224.135:7005,192.168.224.135:7006
        # 最大重定向数，一般设置为5，
      # 不建议设置过大，过大容易引发重定向过多的异常
      max-redirects: 5
    password: 123456
