spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
#        bindings:
#          input:
#            consumer:
#              enable: true
      bindings:
        input:
          destination: TopicTest2
          group: CONSUER_GROUP_DEMO_1

server:
  port: 8082

rocketmq:
  name-server: 127.0.0.1:9876
