spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhongzunfa/{application}
          #username:
          #password:
          search-paths: SC-BOOK-CONFIG
  application:
    name: ch12-1-config-server-placeholders
server:
    port: 9090
logging:
  level:
    root: debug
