spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhongzunfa/spring-cloud-config.git
          search-paths: SC-BOOK-CONFIG
  application:
    name: ch12-9-config-server-high-availability
server:
    port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/