# 定义Spring应用名称，它是一个微服务的名称，一个微服务可拥有多个实例
spring:
  application:
    name: sleuth-provider
  sleuth:
    sampler: # 样本配置
      # 百分比，默认为0.1
      probability: 1.0
      # 速率，每秒30次追踪
      # rate: 30
  zipkin:
    base-url: http://localhost:5001
# 注册到服务治理中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka,http://localhost:1002/eureka



server:
  port: 2001